//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MakeableContract
    {
        public int MakeableContractId { get; set; }
        public int DealId { get; set; }
        public int Level { get; set; }
        public int Denomination { get; set; }
        public string Contract { get; set; }
        public int Declarer { get; set; }
        public string HandViewerInput { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual SysPlayer SysPlayer { get; set; }
    }
}
