//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pair
    {
        public Pair()
        {
            this.DuplicateDeals = new HashSet<DuplicateDeal>();
            this.DuplicateDeals1 = new HashSet<DuplicateDeal>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int EventId { get; set; }
        public decimal Score { get; set; }
        public int Rank { get; set; }
        public int Player1Id { get; set; }
        public int Player2Id { get; set; }
    
        public virtual ICollection<DuplicateDeal> DuplicateDeals { get; set; }
        public virtual ICollection<DuplicateDeal> DuplicateDeals1 { get; set; }
        public virtual Event Event { get; set; }
        public virtual Player Player { get; set; }
        public virtual Player Player1 { get; set; }
    }
}
