//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bridge.Domain.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysPlayer
    {
        public SysPlayer()
        {
            this.DuplicateDeals = new HashSet<DuplicateDeal>();
            this.DuplicateDeals1 = new HashSet<DuplicateDeal>();
        }
    
        public int Id { get; set; }
        public string Player { get; set; }
    
        public virtual ICollection<DuplicateDeal> DuplicateDeals { get; set; }
        public virtual ICollection<DuplicateDeal> DuplicateDeals1 { get; set; }
    }
}
