// <auto-generated />
using Bridge.DataLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Bridge.DataLayer.Migrations
{
    [DbContext(typeof(BridgeContext))]
    [Migration("20180408124941_AddDummyColumn")]
    partial class AddDummyColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Bridge.DataLayer.Models.Deal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BestContract")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("BestContractDeclarer");

                    b.Property<string>("BestContractDisplay")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("BestContractHandViewerInput")
                        .IsRequired();

                    b.Property<int>("BestContractResult");

                    b.Property<int>("EventId");

                    b.Property<string>("HandViewerInput")
                        .IsRequired();

                    b.Property<int>("Index");

                    b.Property<string>("Pbnrepresentation")
                        .IsRequired()
                        .HasColumnName("PBNRepresentation");

                    b.Property<int>("SysVulnerabilityId");

                    b.HasKey("Id");

                    b.HasIndex("BestContractDeclarer");

                    b.HasIndex("EventId");

                    b.HasIndex("SysVulnerabilityId");

                    b.ToTable("Deal");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.DuplicateDeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ContractDisplay")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("DealId");

                    b.Property<int>("Declarer");

                    b.Property<int>("EwpairId")
                        .HasColumnName("EWPairId");

                    b.Property<int>("Ewpercentage")
                        .HasColumnName("EWPercentage");

                    b.Property<string>("HandViewerInput")
                        .IsRequired();

                    b.Property<int>("NspairId")
                        .HasColumnName("NSPairId");

                    b.Property<int>("Nspercentage")
                        .HasColumnName("NSPercentage");

                    b.Property<int>("Result");

                    b.Property<string>("Tricks")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("Declarer");

                    b.HasIndex("EwpairId");

                    b.HasIndex("NspairId");

                    b.ToTable("DuplicateDeal");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsImported");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("SysEventTypeId");

                    b.HasKey("Id");

                    b.HasIndex("SysEventTypeId");

                    b.ToTable("Event");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.Events", b =>
                {
                    b.Property<long>("InStoreId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DummyColumn");

                    b.Property<string>("EventBody")
                        .IsRequired();

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("EventId");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("datetime");

                    b.Property<Guid>("ProcessId");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<int>("UserId");

                    b.HasKey("InStoreId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.MakeableContract", b =>
                {
                    b.Property<int>("MakeableContractId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contract")
                        .IsRequired()
                        .HasMaxLength(10);

                    b.Property<int>("DealId");

                    b.Property<int>("Declarer");

                    b.Property<int>("Denomination");

                    b.Property<string>("HandViewerInput")
                        .IsRequired();

                    b.Property<int>("Level");

                    b.HasKey("MakeableContractId");

                    b.HasIndex("DealId");

                    b.HasIndex("Declarer");

                    b.ToTable("MakeableContract");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.Pair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("EventId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Player1Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<string>("Player2Name")
                        .IsRequired()
                        .HasMaxLength(500);

                    b.Property<int>("Rank");

                    b.Property<decimal>("Score")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Pair");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.SysEventType", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SysEventType");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.SysPlayer", b =>
                {
                    b.Property<int>("Id");

                    b.Property<string>("Player")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("SysPlayer");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.SysVulnerability", b =>
                {
                    b.Property<int>("SysVulnerabilityId");

                    b.Property<string>("SysVulnerabilityName")
                        .IsRequired()
                        .HasColumnType("nchar(50)");

                    b.HasKey("SysVulnerabilityId");

                    b.ToTable("SysVulnerability");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.Deal", b =>
                {
                    b.HasOne("Bridge.DataLayer.Models.SysPlayer", "BestContractDeclarerNavigation")
                        .WithMany("Deal")
                        .HasForeignKey("BestContractDeclarer")
                        .HasConstraintName("FK_Deal_SysPlayer");

                    b.HasOne("Bridge.DataLayer.Models.Event", "Event")
                        .WithMany("Deal")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_Deal_Event")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bridge.DataLayer.Models.SysVulnerability", "SysVulnerability")
                        .WithMany("Deal")
                        .HasForeignKey("SysVulnerabilityId")
                        .HasConstraintName("FK_Deal_SysVulnerability");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.DuplicateDeal", b =>
                {
                    b.HasOne("Bridge.DataLayer.Models.Deal", "Deal")
                        .WithMany("DuplicateDeal")
                        .HasForeignKey("DealId")
                        .HasConstraintName("FK_DuplicateDeal_Deal")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bridge.DataLayer.Models.SysPlayer", "DeclarerNavigation")
                        .WithMany("DuplicateDeal")
                        .HasForeignKey("Declarer")
                        .HasConstraintName("FK_DuplicateDeal_Declarer");

                    b.HasOne("Bridge.DataLayer.Models.Pair", "Ewpair")
                        .WithMany("DuplicateDealEwpair")
                        .HasForeignKey("EwpairId")
                        .HasConstraintName("FK_DuplicateDeal_EWPair");

                    b.HasOne("Bridge.DataLayer.Models.Pair", "Nspair")
                        .WithMany("DuplicateDealNspair")
                        .HasForeignKey("NspairId")
                        .HasConstraintName("FK_DuplicateDeal_NSPair");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.Event", b =>
                {
                    b.HasOne("Bridge.DataLayer.Models.SysEventType", "SysEventType")
                        .WithMany("Event")
                        .HasForeignKey("SysEventTypeId")
                        .HasConstraintName("FK_Event_EventType");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.MakeableContract", b =>
                {
                    b.HasOne("Bridge.DataLayer.Models.Deal", "Deal")
                        .WithMany("MakeableContract")
                        .HasForeignKey("DealId")
                        .HasConstraintName("FK_MakeableContract_Deal")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Bridge.DataLayer.Models.SysPlayer", "DeclarerNavigation")
                        .WithMany("MakeableContract")
                        .HasForeignKey("Declarer")
                        .HasConstraintName("FK_MakeableContract_SysPlayer");
                });

            modelBuilder.Entity("Bridge.DataLayer.Models.Pair", b =>
                {
                    b.HasOne("Bridge.DataLayer.Models.Event", "Event")
                        .WithMany("Pair")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_Pair_Event")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
